###################################################################
# Script Name    : bash_profile
# Description    : DE's bash_profile
# Args           : None
# Author         : Doug Emery
# Email          : hummus.augment_0r@icloud.com
###################################################################
export EDITOR="/usr/bin/vim"
export HISTCONTROL=ignoredups:erasedups
export HISTFILESIZE=1000000
export HISTSIZE=1000000

HOMEBREW_PREFIX=$( [[ -e /opt/homebrew ]] && echo /opt/homebrew || echo /usr/local )
#export FUSEKI_HOME=$HOME/dev/Java/apache-jena-fuseki-3.11.0
#export JENA_HOME=$HOME/dev/Java/apache-jena-3.11.0


PATH=/usr/local/bin:$PATH
PATH=/usr/local/sbin:$PATH
PATH=/opt/homebrew/bin:$PATH
PATH=$PATH:$HOME/bin
PATH=$PATH:$HOME/scripts

PATH=$PATH:$FUSEKI_HOME
PATH=$PATH:$FUSEKI_HOME/bin
PATH=$PATH:$JENA_HOME/bin

PATH=$PATH:$HOME/.cargo/bin

# Poetry install itself in ~/.local for some reason; sigh
PATH=$PATH:$HOME/.local/bin

export PATH

# command aliases
alias l="ls -F"
alias ll="l -lh"
alias lal="ll -a"
alias lll=lal

alias gi="gem install --no-rdoc --no-ri"
alias openx="open -a \"Microsoft Excel\""
alias sxp=strip_xpath
alias vish="vim -c 'set ft=sh'"
alias vivid="vim -c 'colorscheme vividchalk'"
alias wl="wc -l"
alias femacs="emacs --no-init-file"
alias rubymine="open -a RubyMine"
alias subl='open -a "Sublime Text"'
alias tstamp='date +%Y%m%dT%H%M%S-%Z'
##
# directory aliases
##
# print ISO formatted date time
alias idate="date +%FT%T%z"
##
if [[ -f "$HOME/.amazon_keys" ]]; then
  source "$HOME/.amazon_keys";
fi
##
# if [ -d $HOME/.secrets ]; then
#    for file in $HOME/.secrets/*
#    do
#        if [ -s $file ]; then
#           source $file
#        fi
#    done
# fi
##
###############################################################################
# iTerm2 stuff
[[ -f  ~/.iterm2_shell_integration.bash ]] && source ~/.iterm2_shell_integration.bash
##
# Thos the hostname in the iterm2 window bar.
# $1 = type; 0 - both, 1 - tab, 2 - title
# rest = text
setTerminalText () {
    # echo works in bash & zsh
    local mode=$1 ; shift
    echo -ne "\033]$mode;$@\007"
}
stt_both  () { setTerminalText 0 $@; }
stt_tab   () { setTerminalText 1 $@; }
stt_title () { setTerminalText 2 $@; }
##
stt_both $(hostname)
### end iTerm2 stuff
###############################################################################

##
# Rbenv
which -s rbenv && eval "$(rbenv init -)" || echo "WARNING: rbenv not found"

##
# Bash completion
[[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && . "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"


##
if [[ -f $HOME/.ansible-vault-sdbm ]]; then
  source "$HOME/.ansible-vault-sdbm"
fi
##
# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac
##
PYENV_ROOT="$HOME/.pyenv"
if [[ -e $PYENV_ROOT ]]
then
  export PYENV_ROOT
  export PATH="$PYENV_ROOT/shims:$PATH"
  eval "$(pyenv init -)"
fi
##
# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac
##
# Path to the bash it configuration
export BASH_IT="${HOME}/.bash_it"
##
# Lock and Load a custom theme file.
# Leave empty to disable theming.
# location /.bash_it/themes/
export BASH_IT_THEME='bobby'
##
# Some themes can show whether `sudo` has a current token or not.
# Set `$THEME_CHECK_SUDO` to `true` to check every prompt:
THEME_CHECK_SUDO='true'
##
# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'
##
# (Advanced): Change this to the name of the main development branch if
# you renamed it or if it was changed for some reason
# export BASH_IT_DEVELOPMENT_BRANCH='master'
##
# Your place for hosting Git repos. I use this for private repos.
# export GIT_HOSTING='git@git.domain.com'
##
# Don't check mail when opening terminal.
unset MAILCHECK
##
# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'
##
# Set this to the command you use for todo.txt-cli
export TODO="t"
##
# Set this to the location of your work or project folders
#BASH_IT_PROJECT_PATHS="${HOME}/Projects:/Volumes/work/src"
##
# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true
# Set to actual location of gitstatus directory if installed
#export SCM_GIT_GITSTATUS_DIR="$HOME/gitstatus"
# per default gitstatus uses 2 times as many threads as CPU cores, you can change this here if you must
#export GITSTATUS_NUM_THREADS=8
##
# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)
##
# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}
##
# If your theme use command duration, uncomment this to
# enable display of last command duration.
#export BASH_IT_COMMAND_DURATION=true
# You can choose the minimum time in seconds before
# command duration is displayed.
#export COMMAND_DURATION_MIN_SECONDS=1
##
# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true
##
# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt
##
# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1
##
# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1
##
# Load Bash It
source "$BASH_IT"/bash_it.sh

function feature_branch {
  fb_number=$1
  fb_name="${@:2}" # get the rest of the arguments

  fb_normal_name=$(sed 's/[^A-Za-z0-9_-][^A-Za-z0-9_-]*/-/g' <<< "${fb_name}" | tr 'A-Z' 'a-z')
  echo "${fb_number}-${fb_normal_name}"
}
